config/routes.rb
Rails.application.routes.draw do
  get 'blogs' => 'blog#index' , as: 'home'
  get 'blogs/new' => 'blog#new', as: 'new'
  get 'blogs/:id' => 'blog#show', as: 'blog'
  post 'blogs' => 'blog#create'
  get 'blogss/:id/edit' => 'blog#edit', as: 'edit_blog'
  patch 'blogs/:id' => 'blog#update'
  delete 'blogs/:id' => 'blog#destroy', as: 'delete_blog'

  root 'blog#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @blogs = Blog.all
    end

    def show
        @blogs = Blog.find(params[:id])
    end

    def new
        @blog = Blog.new
    end
    def create
        @blog = Blog.create(blog_params)
        if @blog.valid?
            redirect_to home_path
        end
    end
    def destroy
        @blog = Blog.find(params[:id])
        if @blog.destroy    
            redirect_to home_path
        end
    end
    def edit
        @blog = Blog.find(params[:id])
    end
    def update 
        @blog = Blog.find(params[:id])
        if @blog.update(blog_params)
          redirect_to home_path(@book)
        end
    end

    private
        def blog_params
            params.require(:blog).permit(:title, :content)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h2>Edit Blog</h2>
<%= form_with model: @blog, method: :patch do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <br><br>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <br><br>
  <%= form.submit "Edit Blog" %>
<% end %>

<p>
  <%= link_to 'Back to Home', home_path %>
</p>

app/views/blog/index.html.erb
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/assets/button.css"> 
</head>

<body>
  <h1>Blog App</h1>

  <div class='button-container'>
    <% @blogs.each do |blog| %>
      <%= link_to blog.title, blog_path(blog), class: 'blog-button' %>
    <% end %>
  </div>
  <p><%= link_to 'Create a Blog', new_path, class: 'create-button' %></p>
</body>

</html>

app/views/blog/new.html.erb
<h3>Add a New Blog</h3>
<%= form_with model: @blog do |form| %>

  <%= form.label :title %>
  <%= form.text_field :title %>

  <br>
  <%= form.label :content %>
  <%= form.text_field :content %>

  <br>
  <%= form.submit 'Add Blog' %>

<% end %>
<p><%= link_to 'Homeless', home_path %></p>

app/views/blog/show.html.erb
<h3><%= @blogs.title %></h3>
<p><%= @blogs.content %></p>
<%= link_to 'Update Blog',
    edit_blog_path(@blogs) %>
<p><%= link_to 'Homeless', home_path %></p>
<%= button_to 'Remove Book', delete_blog_path, method: 'delete' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>